### ISSUE TITLE
:arrow_up: Consider pyenv

### ISSUE THREAD

**Issue by jefftriplett** [wsvincent/installpython3.com#1]
You might consider adding docs for [pyenv](https://github.com/pyenv/pyenv). pyenv requires an extra step or two but overall it is less fragile and easier to upgrade/work with than Homebrew's Python. It works on Linux and has a Windows port too, but I haven't tried those. 

If you need to work with multiple version of Python (think 3.5, 3.6, and 3.7) and you need a way to test against those, then it's really your best shot. Another benefit is that it won't break your projects because you upgrade your Homebrew Python's version.

**Comment by wsvincent** [comment]
Hi Jeff! Let's discuss this further today. I'm not super familiar with pyenv to be honest but might indeed be better.
